# Generated by Django 6.0.4 on 2026-08-23 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_agent_can_order_agentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="Where paperwork for this address goes. Blank uses the account's email.", max_length=254),
        ),
        migrations.AddField(
            model_name='address',
            name='contact_phone',
            field=models.CharField(blank=True, help_text="Person to call about this address. Blank uses the account's number.", max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a phone number using digits, spaces, +, - or brackets.', regex='^[0-9+()\\-\\s]{7,20}$')]),
        ),
    ]
