# Generated by Django 6.0.4 on 2026-08-23 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    help_text only — the contact fields became mandatory at the API boundary
    (AddressSerializer), not in the database, so this produces no SQL. The
    column stays nullable so addresses saved before the requirement still load.
    """


    dependencies = [
        ('accounts', '0007_address_contact_email_address_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Where paperwork for this address goes.', max_length=254),
        ),
        migrations.AlterField(
            model_name='address',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Person to call about this address.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a phone number using digits, spaces, +, - or brackets.', regex='^[0-9+()\\-\\s]{7,20}$')]),
        ),
    ]
