# Generated by Django 6.0.4 on 2026-07-09 07:56

import core.utils.images
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_sampleorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_screenshot',
            field=core.utils.images.CompressedImageField(blank=True, help_text='Screenshot of payment success screen uploaded by buyer', null=True, upload_to='payment_receipts/'),
        ),
    ]
