# Generated by Django 6.0.4 on 2026-08-05 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Bytes', null=True)),
                ('alt_text', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('folder', models.CharField(blank=True, max_length=255, null=True)),
                ('variants', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Library',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachable_type', models.CharField(choices=[('product', 'Product'), ('product_color', 'Product colour'), ('variation', 'Product variation'), ('category', 'Category'), ('banner', 'Hero slide / banner'), ('lookbook', 'Lookbook')], max_length=32)),
                ('attachable_id', models.BigIntegerField()),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('gallery', 'Gallery'), ('swatch', 'Swatch')], default='gallery', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='medialib.mediaasset')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['attachable_type', 'attachable_id', 'sort_order'], name='idx_attach_entity_order')],
                'constraints': [models.UniqueConstraint(fields=('media', 'attachable_type', 'attachable_id', 'role'), name='uniq_media_attachment_role')],
            },
        ),
    ]
