# Generated by Django 6.0.4 on 2026-04-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.PositiveIntegerField(default=10, help_text='Minimum Order Quantity for B2B clients'),
        ),
    ]
