# Generated by Django 6.0.4 on 2026-07-09 07:56

import core.utils.images
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_variationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=core.utils.images.CompressedImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=core.utils.images.CompressedImageField(upload_to='hero_slides/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=core.utils.images.CompressedImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=core.utils.images.CompressedImageField(upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='image',
            field=core.utils.images.CompressedImageField(blank=True, null=True, upload_to='variations/'),
        ),
        migrations.AlterField(
            model_name='variationimage',
            name='image',
            field=core.utils.images.CompressedImageField(upload_to='variations/gallery/'),
        ),
    ]
