# Generated by Django 6.0.4 on 2026-07-10 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_category_image_alter_heroslide_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a main category. Set this to nest it as a sub-category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='Sub-categories (within the selected category) this product should also appear under.', limit_choices_to={'parent__isnull': False}, related_name='products_in_subcategory', to='products.category'),
        ),
    ]
