# Generated by Django 6.0.4 on 2026-07-10 20:49

import re

import core.utils.images
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_pieces_from_breakdown_string(apps, schema_editor):
    """
    Existing SizeSetBreakdown rows default to pieces=1, which would be
    wrong for real multi-piece sets (e.g. "1xL, 1xXL, 1xXXL, 1x3XL" is
    actually 4 pieces) and would silently break the new auto-price-multiply
    logic for any admin who starts using per-piece pricing on an existing
    breakdown. Split on commas and take the count prefix of each token —
    matching must be anchored to the token start, since size labels like
    "3XL"/"4XL"/"5XL" themselves start with a digit followed by "X" and
    would otherwise be miscounted as extra tokens (e.g. a naive scan of
    "1x3XL" finds both "1x" and "3X").
    """
    SizeSetBreakdown = apps.get_model('products', 'SizeSetBreakdown')
    for breakdown in SizeSetBreakdown.objects.all():
        total = 0
        for token in (breakdown.breakdown_string or '').split(','):
            match = re.match(r'^\s*(\d+)\s*[xX]', token)
            if match:
                total += int(match.group(1))
        if total == 0:
            total = 1
        if breakdown.pieces != total:
            breakdown.pieces = total
            breakdown.save(update_fields=['pieces'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_category_parent_product_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizesetbreakdown',
            name='pieces',
            field=models.PositiveIntegerField(default=1, help_text='Total garment pieces in this breakdown, e.g. "1xL, 1xXL, 1xXXL, 1x3XL" = 4. Used to auto-calculate a variation\'s total MRP/price from its per-piece price.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RunPython(backfill_pieces_from_breakdown_string, noop),
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', core.utils.images.CompressedImageField(upload_to='products/colors/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Color Image',
                'verbose_name_plural': 'Product Color Images',
                'ordering': ['product', 'color', 'order', 'id'],
            },
        ),
    ]
