# Generated by Django 6.0.4 on 2026-08-17 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_sizesetbreakdown_pieces_productcolorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizesetbreakdown',
            name='label',
            field=models.CharField(help_text='Human-readable label shown in the dropdown, e.g. "1xL, 2xXL, 1x2XL, 1x3XL"', max_length=255),
        ),
        migrations.AlterField(
            model_name='sizesetbreakdown',
            name='pieces',
            field=models.PositiveIntegerField(default=1, help_text='Total garment pieces in this breakdown, e.g. "1xL, 1xXL, 1x2XL, 1x3XL" = 4. Used to auto-calculate a variation\'s total MRP/price from its per-piece price.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
