# Generated by Django 6.0.4 on 2026-08-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_size_xxl_to_2xl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='Short code used as the SKU prefix, e.g. "PJ100". Letters, digits and hyphens.', max_length=32, null=True, unique=True),
        ),
    ]
