# Generated by Django 6.0.4 on 2026-08-18 10:56

import core.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Used as the meta description on the category page. Left blank, one is generated from the category name.'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Overrides the search-result description. Up to 160 characters. Blank uses the generated one.', max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Overrides the search-result title. Up to 70 characters. Blank uses the generated one.', max_length=70),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=core.utils.images.CompressedImageField(blank=True, help_text='Image used when the product is shared on WhatsApp or social. Blank falls back to the cover image, then the site card.', null=True, upload_to='products/og/'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
