# Generated by Django 6.0.4 on 2026-08-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_moq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Fit", "Fabric", "Length"', max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('multi_select', models.BooleanField(default=False, help_text='Allow more than one option on a product (e.g. Length).')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive attributes are hidden from the product editor. Deactivate rather than delete — deleting takes the values off every product that used them.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order, in the editor and on the product page.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.attribute')),
            ],
            options={
                'ordering': ['order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_options',
            field=models.ManyToManyField(blank=True, help_text='Fit, fabric, length and so on. Picked, not typed.', related_name='products', to='products.attributeoption'),
        ),
    ]
