// Single source of truth for anything that has to be a real, absolute URL.
//
// Canonicals, Open Graph tags and JSON-LD all need the public origin, and a
// client-rendered SPA has no server to derive it from. VITE_SITE_URL lets a
// preview deployment point at itself; production falls back to the live domain.
export const SITE_URL = (import.meta.env.VITE_SITE_URL || 'https://www.pronounjeans.com')
  .trim()
  .replace(/\/+$/, '');

export const SITE_NAME = 'Pronoun Jeans';
export const TITLE_SUFFIX = ` | ${SITE_NAME}`;

// Generated by scripts/generate-og-image.py from public/logo.png.
export const DEFAULT_OG_IMAGE = {
  url: `${SITE_URL}/og-default.jpg`,
  width: 1200,
  height: 630,
};

// Canonicals must be absolute, and must never carry a query string: /catalog
// and /catalog?subcategory=cargos are the same page to Google, and letting the
// filter into the canonical would split their signals. The trailing slash is
// collapsed for the same reason.
export function absoluteUrl(path = '/') {
  const [pathname] = String(path).split(/[?#]/);
  const rooted = pathname.startsWith('/') ? pathname : `/${pathname}`;
  const trimmed = rooted.length > 1 ? rooted.replace(/\/+$/, '') : '/';
  return `${SITE_URL}${trimmed}`;
}

// Google renders roughly 155 characters of a description on desktop. Copy
// written by hand stays inside that; descriptions built from live product or
// category names can overrun, so they get cut on a word boundary rather than
// mid-word.
export function clampDescription(text, max = 160) {
  const normalised = String(text ?? '').replace(/\s+/g, ' ').trim();
  if (normalised.length <= max) return normalised;
  const cut = normalised.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(' ');
  return `${(lastSpace > 0 ? cut.slice(0, lastSpace) : cut).replace(/[\s,;:—–-]+$/, '')}…`;
}
